-- MySQL Script generated by MySQL Workbench
-- Thu Nov 19 17:54:53 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tzfc_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tzfc_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tzfc_db` DEFAULT CHARACTER SET utf8 ;
USE `tzfc_db` ;

-- -----------------------------------------------------
-- Table `tzfc_db`.`Tab_SellHouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tzfc_db`.`Tab_SellHouse` ;

CREATE TABLE IF NOT EXISTS `tzfc_db`.`Tab_SellHouse` (
  `shid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) NULL,
  `rooms` TINYINT NULL DEFAULT 0 COMMENT '几室几厅几卫',
  `halls` TINYINT NULL DEFAULT 0 COMMENT '几室几厅几卫',
  `bathrooms` TINYINT NULL DEFAULT 0 COMMENT '几室几厅几卫',
  `size` VARCHAR(50) NULL COMMENT '面积',
  `price` DECIMAL(6,2) NULL DEFAULT 0.00 COMMENT '价格的值',
  `unit_price` DECIMAL(6,0) NULL DEFAULT 0,
  `community` VARCHAR(45) NULL,
  `floors` SMALLINT NULL DEFAULT 0 COMMENT '楼层',
  `floors_total` SMALLINT NULL DEFAULT 0 COMMENT '总层数',
  `house_type` TINYINT NULL DEFAULT 0,
  `decor` TINYINT NULL DEFAULT 0,
  `orientation` TINYINT NULL DEFAULT 0,
  `rights_len` TINYINT NULL DEFAULT 0,
  `rights_type` TINYINT NULL DEFAULT 0,
  `rights_from` VARCHAR(15) NULL,
  `primary_school` VARCHAR(100) NULL,
  `junior_school` VARCHAR(100) NULL,
  `details` VARCHAR(20000) NULL COMMENT '详情',
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `uid` INT NOT NULL,
  PRIMARY KEY (`shid`),
  CONSTRAINT `fk_Tab_SellHouse_Tab_User1`
    FOREIGN KEY (`uid`)
    REFERENCES `tzfc_db`.`Tab_User` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tab_SellHouse_Tab_User1_idx` ON `tzfc_db`.`Tab_SellHouse` (`uid` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `tzfc_db`;

DELIMITER $$

USE `tzfc_db`$$
DROP TRIGGER IF EXISTS `tzfc_db`.`Tab_SellHouse_BEFORE_INSERT` $$
USE `tzfc_db`$$
CREATE TRIGGER `tzfc_db`.`Tab_SellHouse_BEFORE_INSERT` BEFORE INSERT ON `Tab_SellHouse` FOR EACH ROW
BEGIN
set @temp_now = now(); set new.`create_time` = @temp_now ; set new.`update_time` = @temp_now ;
END$$


USE `tzfc_db`$$
DROP TRIGGER IF EXISTS `tzfc_db`.`Tab_SellHouse_BEFORE_UPDATE` $$
USE `tzfc_db`$$
CREATE DEFINER = CURRENT_USER TRIGGER `tzfc_db`.`Tab_SellHouse_BEFORE_UPDATE` BEFORE UPDATE ON `Tab_SellHouse` FOR EACH ROW
BEGIN
set new.`update_time` = now() ;
END$$


DELIMITER ;
