-- MySQL Script generated by MySQL Workbench
-- Wed Nov 18 23:35:54 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tzfc_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tzfc_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tzfc_db` DEFAULT CHARACTER SET utf8 ;
USE `tzfc_db` ;

-- -----------------------------------------------------
-- Table `tzfc_db`.`Tab_Area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tzfc_db`.`Tab_Area` ;

CREATE TABLE IF NOT EXISTS `tzfc_db`.`Tab_Area` (
  `aid` INT NOT NULL AUTO_INCREMENT COMMENT '区域ID',
  `area_name` VARCHAR(45) NULL COMMENT '区域名',
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`aid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tzfc_db`.`Tab_Community`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tzfc_db`.`Tab_Community` ;

CREATE TABLE IF NOT EXISTS `tzfc_db`.`Tab_Community` (
  `cid` INT UNIQUE NOT NULL AUTO_INCREMENT COMMENT '小区ID',
  `cname` VARCHAR(45) NULL COMMENT '小区名',
  `pinyin` VARCHAR(45) NULL COMMENT '拼音首字母',
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  PRIMARY KEY (`cid`));

USE `tzfc_db` ;


-- -----------------------------------------------------
-- View `tzfc_db`.`view_community`
-- -----------------------------------------------------
--DROP VIEW IF EXISTS `tzfc_db`.`view_community` ;
--USE `tzfc_db`;
--CREATE  OR REPLACE VIEW `view_community` AS
--SELECT c.cid, c.cname, c.pinyin, a.aid, a.area_name FROM `tzfc_db`.`Tab_Community` c, `tzfc_db`.`Tab_Area` a WHERE a.aid = c.aid;
--USE `tzfc_db`;

DELIMITER $$

USE `tzfc_db`$$
DROP TRIGGER IF EXISTS `tzfc_db`.`Tab_Area_BEFORE_INSERT` $$
USE `tzfc_db`$$
CREATE TRIGGER `tzfc_db`.`Tab_Area_BEFORE_INSERT` BEFORE INSERT ON `Tab_Area` FOR EACH ROW
BEGIN
set @temp_now = now(); set new.`create_time` = @temp_now ; set new.`update_time` = @temp_now ;
END$$


USE `tzfc_db`$$
DROP TRIGGER IF EXISTS `tzfc_db`.`Tab_Area_BEFORE_UPDATE` $$
USE `tzfc_db`$$
CREATE TRIGGER `tzfc_db`.`Tab_Area_BEFORE_UPDATE` BEFORE UPDATE ON `Tab_Area` FOR EACH ROW
BEGIN
set new.`update_time` = now() ;
END$$


USE `tzfc_db`$$
DROP TRIGGER IF EXISTS `tzfc_db`.`Tab_Community_BEFORE_INSERT` $$
USE `tzfc_db`$$
CREATE TRIGGER `tzfc_db`.`Tab_Community_BEFORE_INSERT` BEFORE INSERT ON `Tab_Community` FOR EACH ROW
BEGIN
set @temp_now = now(); set new.`create_time` = @temp_now ; set new.`update_time` = @temp_now ;
END$$


USE `tzfc_db`$$
DROP TRIGGER IF EXISTS `tzfc_db`.`Tab_Community_BEFORE_UPDATE` $$
USE `tzfc_db`$$
CREATE TRIGGER `tzfc_db`.`Tab_Community_BEFORE_UPDATE` BEFORE UPDATE ON `Tab_Community` FOR EACH ROW
BEGIN
set new.`update_time` = now() ;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;






-- -----------------------------------------------------
-- Table `tzfc_db`.`Tab_Area` data
-- -----------------------------------------------------
INSERT INTO `tzfc_db`.`Tab_Area`(`area_name`) VALUES ('市区');
INSERT INTO `tzfc_db`.`Tab_Area`(`area_name`) VALUES ('城中');
INSERT INTO `tzfc_db`.`Tab_Area`(`area_name`) VALUES ('城东');
INSERT INTO `tzfc_db`.`Tab_Area`(`area_name`) VALUES ('城南');
INSERT INTO `tzfc_db`.`Tab_Area`(`area_name`) VALUES ('城西');
INSERT INTO `tzfc_db`.`Tab_Area`(`area_name`) VALUES ('城北');
INSERT INTO `tzfc_db`.`Tab_Area`(`area_name`) VALUES ('其他地区');




-- -----------------------------------------------------
-- Table `tzfc_db`.`Tab_Community` data
-- -----------------------------------------------------
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('美好上郡', 'mhsj');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('碧桂园', 'bgy');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('永兴花园', 'yxhy');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('祥云花园', 'xyhy');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('宏基花园', 'hjhy');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('华辰尊园', 'hczy');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('莲花六区', 'lhlq');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('莲花五区', 'lhwq');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('水岸豪庭', 'saht');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('东河阳光', 'dhyg');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('阳光新城', 'ygxc');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('稻河湾', 'dhw');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('森园小区', 'syxq');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('玉堂花园', 'ythy');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('鹏欣丽都', 'pxld');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('教工三村', 'jgsc');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('财富广场', 'cfgc');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('五一路', 'wyl');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('工人新村', 'grxc');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('福寿苑', 'fsy');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('怡和花园', 'yhhy');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('新世界花园', 'xsjhy');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('宫涵花园', 'ghhy');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('供电新苑', 'gdxy');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('西域绿洲', 'xylz');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('盛塘花苑', 'sthy');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('金水湾', 'jsw');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('莲花八区', 'lhbq');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('坡子街', 'pzj');
INSERT INTO `tzfc_db`.`Tab_Community`(`cname`, `pinyin`) VALUES ('凤城国际', 'fhfj');



