-- MySQL Script generated by MySQL Workbench
-- Tue Nov 24 15:13:46 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tzfc_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tzfc_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tzfc_db` DEFAULT CHARACTER SET utf8 ;
USE `tzfc_db` ;

-- -----------------------------------------------------
-- Table `tzfc_db`.`Tab_SellHouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tzfc_db`.`Tab_SellHouse` ;

CREATE TABLE IF NOT EXISTS `tzfc_db`.`Tab_SellHouse` (
  `hid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) NULL,
  `rooms` TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '几室几厅几卫',
  `halls` TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '几室几厅几卫',
  `bathrooms` TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '几室几厅几卫',
  `size` MEDIUMINT UNSIGNED NULL DEFAULT 0 COMMENT '面积',
  `price` DECIMAL(6,2) UNSIGNED NULL DEFAULT 0.00 COMMENT '价格的值',
  `unit_price` DECIMAL(6,0) UNSIGNED NULL DEFAULT 0,
  `community` VARCHAR(45) NULL,
  `cid` INT NULL COMMENT '小区ID',
  `aid` INT NULL COMMENT '区域ID',
  `floors` SMALLINT NULL DEFAULT 0 COMMENT '楼层',
  `floors_total` SMALLINT NULL DEFAULT 0 COMMENT '总层数',
  `house_type` TINYINT UNSIGNED NULL DEFAULT 0,
  `decor` TINYINT UNSIGNED NULL DEFAULT 0,
  `orientation` TINYINT UNSIGNED NULL DEFAULT 0,
  `rights_len` TINYINT UNSIGNED NULL DEFAULT 0,
  `rights_type` TINYINT UNSIGNED NULL DEFAULT 0,
  `rights_from` SMALLINT UNSIGNED NULL,
  `primary_school` VARCHAR(100) NULL,
  `junior_school` VARCHAR(100) NULL,
  `details` VARCHAR(20000) NULL COMMENT '详情',
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `uid` INT NOT NULL COMMENT '用户ID',
  PRIMARY KEY (`hid`),
  CONSTRAINT `fk_Tab_SellHouse_Tab_User1`
    FOREIGN KEY (`uid`)
    REFERENCES `tzfc_db`.`Tab_User` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tab_SellHouse_Tab_User1_idx` ON `tzfc_db`.`Tab_SellHouse` (`uid` ASC);

CREATE INDEX `INDEX_Tab_SellHouse_HOUSE_TYPE` ON `tzfc_db`.`Tab_SellHouse` (`rooms` ASC, `halls` ASC, `bathrooms` ASC);

USE `tzfc_db`;

DELIMITER $$

USE `tzfc_db`$$
DROP TRIGGER IF EXISTS `tzfc_db`.`Tab_SellHouse_BEFORE_INSERT` $$
USE `tzfc_db`$$
CREATE TRIGGER `tzfc_db`.`Tab_SellHouse_BEFORE_INSERT` BEFORE INSERT ON `Tab_SellHouse` FOR EACH ROW
BEGIN
set @temp_now = now(); set new.`create_time` = @temp_now ; set new.`update_time` = @temp_now ;
END$$


USE `tzfc_db`$$
DROP TRIGGER IF EXISTS `tzfc_db`.`Tab_SellHouse_BEFORE_UPDATE` $$
USE `tzfc_db`$$
CREATE DEFINER = CURRENT_USER TRIGGER `tzfc_db`.`Tab_SellHouse_BEFORE_UPDATE` BEFORE UPDATE ON `Tab_SellHouse` FOR EACH ROW
BEGIN
set new.`update_time` = now() ;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
