-- MySQL Script generated by MySQL Workbench
-- Mon Jan 11 00:09:26 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tzfc_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tzfc_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tzfc_db` DEFAULT CHARACTER SET utf8 ;
USE `tzfc_db` ;

-- -----------------------------------------------------
-- Table `tzfc_db`.`Tab_RentHouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tzfc_db`.`Tab_RentHouse` ;

CREATE TABLE IF NOT EXISTS `tzfc_db`.`Tab_RentHouse` (
  `hid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(500) NULL,
  `rooms` TINYINT UNSIGNED NULL DEFAULT 0,
  `halls` TINYINT UNSIGNED NULL DEFAULT 0,
  `bathrooms` TINYINT UNSIGNED NULL DEFAULT 0,
  `size` MEDIUMINT UNSIGNED NULL DEFAULT 0 COMMENT '面积',
  `price` DECIMAL(7,0) UNSIGNED NULL DEFAULT 0 COMMENT '价格的值',
  `rent_type` TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '出租方式',
  `rentpay_type` TINYINT UNSIGNED NULL DEFAULT 0 COMMENT '租金缴纳方式',
  `support_device` VARCHAR(200) NULL,
  `community` VARCHAR(45) NULL,
  `cid` INT NULL,
  `aid` INT NULL,
  `floors` SMALLINT NULL DEFAULT 0 COMMENT '楼层',
  `floors_total` SMALLINT NULL DEFAULT 0 COMMENT '总层数',
  `house_type` TINYINT UNSIGNED NULL DEFAULT 0,
  `decor` TINYINT UNSIGNED NULL DEFAULT 0,
  `orientation` TINYINT UNSIGNED NULL DEFAULT 0,
  `images` VARCHAR(10000) NULL,
  `details` TEXT NULL COMMENT '详情',
  `create_time` DATETIME NULL,
  `update_time` DATETIME NULL,
  `uid` INT NOT NULL,
  PRIMARY KEY (`hid`),
  CONSTRAINT `fk_Tab_RentHouse_Tab_User1`
    FOREIGN KEY (`uid`)
    REFERENCES `tzfc_db`.`Tab_User` (`uid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tab_RentHouse_Tab_User1_idx` ON `tzfc_db`.`Tab_RentHouse` (`uid` ASC);

CREATE INDEX `INDEX_Tab_RentHouse_HOUSE_TYPE` ON `tzfc_db`.`Tab_RentHouse` (`rooms` ASC, `halls` ASC, `bathrooms` ASC);

CREATE INDEX `INDEX_Tab_RentHouse_UpdateTime` ON `tzfc_db`.`Tab_RentHouse` (`update_time` DESC);

USE `tzfc_db`;

DELIMITER $$

USE `tzfc_db`$$
DROP TRIGGER IF EXISTS `tzfc_db`.`Tab_RentHouse_BEFORE_INSERT` $$
USE `tzfc_db`$$
CREATE DEFINER = CURRENT_USER TRIGGER `tzfc_db`.`Tab_RentHouse_BEFORE_INSERT` BEFORE INSERT ON `Tab_RentHouse` FOR EACH ROW
BEGIN
set @temp_now = now(); set new.`create_time` = @temp_now ; set new.`update_time` = @temp_now ;
END$$


USE `tzfc_db`$$
DROP TRIGGER IF EXISTS `tzfc_db`.`Tab_RentHouse_BEFORE_UPDATE` $$
USE `tzfc_db`$$
CREATE DEFINER = CURRENT_USER TRIGGER `tzfc_db`.`Tab_RentHouse_BEFORE_UPDATE` BEFORE UPDATE ON `Tab_RentHouse` FOR EACH ROW
BEGIN
set new.`update_time` = now() ;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
